Create doc
I've been attempting to make a  clock that will address in the form of year, month, and date the days until a game is released, the language being used is Ruby and I'm coding through RubyMine.
the games I chose are Crash Bandicoot, Genshin Impact, and Call of Duty 6: Black Ops Cold War.
the variables are set using Time.mktime ( year, month, day ) however it seems as though I'm running into a problem running the code; the code gives me the error: 
Traceback (most recent call last):
C:/Users/Giselle Vega/RubymineProjects/Testing/Clock.rb:18:in `<main>': undefined method `/' for 2020-07-12 00:00:00 -0400:Time (NoMethodError) at first I thought there was a problem with the date format and attempted to change it for the entries to use day, month and year. but no results, I honestly am at a loss considering I don't seem to understand why it's addressing the method is undefined.  Any Ideas?  
I appreciate it, thank you!